name: lacework-iac-example 

# Controls when the workflow will run 
on: 
  schedule: 
    - cron: '0 0 * * *'  # Runs every day at midnight UTC 

  # Also allow manual triggering of the workflow 
  workflow_dispatch: 

permissions: 
  security-events: write  # Grant permission to upload SARIF files for Code Scanning 
  contents: read  # Grant permission to read the contents of the repository
  actions: read 

jobs: 
  daily_scan: 
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu environment 

    steps: 
      # Step 1: Install the Lacework CLI and SCA component 
      - name: Install Lacework CLI 
        run: | 
          # Download and install the Lacework CLI using a shell script 

          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash 
          # Configure the Lacework CLI with account, API key, and secret from GitHub secrets 
          lacework configure -a ${{ secrets.LW_ACCOUNT }}.lacework.net -k ${{ secrets.LW_API_KEY }} -s ${{ secrets.LW_API_SECRET }} --noninteractive 
          # Install the Software Composition Analysis (SCA) component 
          lacework component install sca 

      # Step 2: Check out the main branch 
      - name: Checkout main branch 
        uses: actions/checkout@v3  # Use the checkout action to pull the main branch code 
        with: 
          ref: main  # Specify the main branch 
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication 

      # Step 3: Run the Lacework IaC scan on the main branch and generate SARIF output 
      - name: Run Lacework SCA Scan on Main Branch 
        run: |
            env | grep "GITHUB_\|LW_\|CI_" > env.list
            echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
            echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
            echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
            echo "EXIT_FLAG=CRITICAL=1" >> env.list
      - name: Scan the repo for vulnerabilities in IaC
        run: |
            docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec:stable lacework iac scan --directory=.

