name: Lacework Code Security Scan

on:
  push:
    branches: ["**"]

jobs:

  push_scanning:
    name: Push Scanning
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Starting Lacework SCA scan on push
        run: echo "Starting Lacework SCA scan on push"

      - name: Run Lacework scan
        run: lacework sca scan ./ -f sarif -o lacework-scan.sarif

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3  # Use the GitHub action to upload SARIF
        with:
            sarif_file: lacework-scan.sarif  # Path to the SARIF file

